#################################################################################
#
#	This file is part of CG4.
#
#	Copyright (c) Inbar Donag and Maxim Levitsky
#
#    CG4 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    CG4 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with CG4.  If not, see <http://www.gnu.org/licenses/>.
#
##################################################################################


LDFLAGS += -g -flto=3 -O3 -march=core2 -Wall

.PHONY: all

all:
	$(MAKE) -C renderer
	$(MAKE) -C engine
	
	$(MAKE) -C model/mtlparser
	$(MAKE) -C model/objparser
	$(MAKE) -C model
	
	qmake -o gui/Makefile gui/make.pro
	$(MAKE) -C gui
	
	$(CXX) $(LDFLAGS) -o cgrender \
		renderer/librenderer.a engine/libengine.a   \
		model/libmodel.a model/mtlparser/libmtlparser.a model/objparser/libobjparser.a model/libmodel.a \
		gui/libgui.a gui/.objs/qrc_resources.o -lpng12 -lQtGui -lQtCore -lpthread
	
clean:
	rm -f cgrender
	$(MAKE) -C renderer clean
	$(MAKE) -C engine  clean
	$(MAKE) -C model clean
	$(MAKE) -C model/mtlparser clean
	$(MAKE) -C model/objparser clean
	$(MAKE) -C gui clean
	rm -f gui/libgui.a
	
cleanall: clean
	rm -f gui/Makefile
	rm -rf gui/autogenerated
