#################################################################################
#
#	This file is part of CG4.
#
#	Copyright (c) Inbar Donag and Maxim Levitsky
#
#    CG4 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    CG4 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with CG4.  If not, see <http://www.gnu.org/licenses/>.
#
##################################################################################


LDFLAGS += -g -flto -O3 -march=core2 -Wall

.PHONY: all

all:
	$(MAKE) -C renderer
	$(MAKE) -C model
	$(MAKE) -C engine

	$(MAKE) -C IO/mtlparser
	$(MAKE) -C IO/objparser
	$(MAKE) -C IO
	
	qmake -o gui/Makefile gui/make.pro
	make -j1 -C gui
	
	g++ $(LDFLAGS) -o cgrender \
		renderer/librenderer.a engine/libengine.a model/libmodel.a  \
		IO/libio.a IO/mtlparser/libmtlparser.a IO/objparser/libobjparser.a \
		  gui/libgui.a -lQtGui -lQtCore -lpng
	
clean:
	rm -f cgrender
	$(MAKE) -C renderer clean
	$(MAKE) -C engine  clean
	$(MAKE) -C model clean
	$(MAKE) -C IO  clean
	$(MAKE) -C IO/mtlparser clean
	$(MAKE) -C IO/objparser clean
	$(MAKE) -C gui clean
	
cleanall: clean
	rm -f gui/Makefile
	rm -rf gui/autogenerated
