//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CG4.rc
//
#define IDD_ABOUTBOX                    100
#define ID_INDICATOR_PROGRESS_PANE      101
#define IDR_MAINFRAME                   128
#define IDR_CG4TYPE                     129
#define IDD_LIGHTS_DLG                  134
#define IDD_MATERIAL_DLG                136
#define IDD_SETTINGS                    139
#define IDD_RENDERTOFILE_DIALOG         141
#define IDB_BITMAP1                     144
#define IDB_ABOUT_BMP                   144
#define IDC_LIGHT_SPACE                 1010
#define IDC_RADIO_LIGHT1                1017
#define IDC_RADIO_LIGHT2                1018
#define IDC_RADIO_LIGHT3                1019
#define IDC_RADIO_LIGHT4                1020
#define IDC_RADIO_LIGHT5                1021
#define IDC_RADIO_LIGHT6                1022
#define IDC_RADIO_LIGHT7                1023
#define IDC_RADIO_LIGHT8                1024
#define IDC_AMBL_COLOR_R                1025
#define IDC_LIGHT_ENABLED               1026
#define IDC_AMBL_COLOR_G                1027
#define IDC_AMBL_COLOR_B                1028
#define IDC_LIGHT_COLOR_R               1029
#define IDC_LIGHT_COLOR_G               1030
#define IDC_LIGHT_COLOR_B               1031
#define IDC_LIGHT_POS_X                 1032
#define IDC_LIGHT_POS_Y                 1033
#define IDC_LIGHT_POS_Z                 1034
#define IDC_LIGHT_DIR_X                 1035
#define IDC_LIGHT_DIR_Y                 1036
#define IDC_LIGHT_DIR_Z                 1037
#define IDC_LIGHT_TYPE                  1038
#define IDC_MATERIAL_AMBIENT            1039
#define IDC_LIGHT_COLOR_R2              1039
#define IDC_MATERIAL_DIFFUSE            1040
#define IDC_DISTANCE                    1040
#define IDC_LIGHT_COLOR_G2              1040
#define IDC_MATERIAL_SHININESS          1041
#define IDC_LIGHT_COLOR_B2              1041
#define IDC_MATERIAL_SPECULAR           1042
#define IDC_DISTANCE_TEXTBOX            1042
#define IDC_ROTATION_SENSIVITY          1044
#define IDC_TRANSLATION_SENSIVETY       1045
#define IDC_SCALING_SENSIVETY           1046
#define IDC_FINESS_SLIDER               1047
#define IDC_FINESS_TEXTBOX              1048
#define IDC_CHANGE_DEFAULT_OBJECT_COLOR 1049
#define IDC_OBJECT_COLOR                1050
#define IDC_CHANGE_BACKGROND_COLOR      1051
#define IDC_FINESS_APPLY                1052
#define IDC_CHANGE_FOG_COLOR            1052
#define IDC_BACKGROUND_COLOR            1053
#define IDC_COLOR_OVERRIDE_CHECK        1054
#define IDC_SENSIVETY_RESET             1055
#define IDC_FOG_COLOR                   1055
#define IDC_LIGTHING_RESET              1056
#define IDC_MATRIAL_RESET               1056
#define IDC_SPIN1                       1057
#define IDC_SPIN2                       1058
#define IDC_SPIN_AMBI_R                 1059
#define IDC_SPIN4                       1060
#define IDC_SPIN_AMBI_G                 1061
#define IDC_SPIN6                       1062
#define IDC_SPIN_POS_X                  1062
#define IDC_SPIN7                       1063
#define IDC_RENDER_FILE_LOCATION        1063
#define IDC_SPIN_POS_Y                  1063
#define IDC_SPIN8                       1064
#define IDC_RENDER_FILE_CHOOSE          1064
#define IDC_SPIN_POS_Z                  1064
#define IDC_SPIN9                       1065
#define IDC_RENDER_FILE_X               1065
#define IDC_SPIN_DIR_X                  1065
#define IDC_SPIN10                      1066
#define IDC_RENDER_FILE_Y               1066
#define IDC_TEXTURE_FILENAME            1066
#define IDC_SPIN_DIR_Y                  1066
#define IDC_SPIN11                      1067
#define IDC_BUTTON1                     1067
#define IDC_TEXTURE_FILENAME_CHOOSE     1067
#define IDC_SPIN_DIR_Z                  1067
#define IDC_SPIN_AMBI_B                 1068
#define IDC_SPIN3                       1069
#define IDC_SPIN5                       1070
#define IDC_SPIN12                      1071
#define IDC_CUTOFF_ANGLE_TEXTBOX        1072
#define IDC_SPIN_SPOT_ANGLE             1073
#define IDC_FOG_INTENSITY               1075
#define IDC_BTN_COLOR_RESET             1076
#define IDC_BTN_TEXTURE_RESET           1077
#define IDC_BTN_NO_TEXTURE              1078
#define IDC_TXT_FOG_START               1079
#define IDC_TXT_FOG_END                 1080
#define IDC_FOG_MODE                    1082
#define IDC_CAN_CAST_SHADOW             1083
#define IDC_LIGHT_DEBUG                 1084
#define IDC_Z_BIAS_MULITPLIER           1085
#define IDC_MAX_Z_BIAS                  1086
#define IDC_CHECK_PCF                   1088
#define IDC_PCF_TAPS                    1089
#define IDC_POISON_EN                   1090
#define IDC_SHADOW_MAP_RES              1091
#define IDC_SPIN_MAX_Z_BIAS             1092
#define IDC_SPIN_Z_MULTIPLY             1094
#define IDC_SPIN_PCF_TAPS               1095
#define IDC_SPIN_SHADOW_MAP_RES         1096
#define IDC_SHADOWS_RESET               1097
#define IDC_COMBO_TEXTURE_MODE          1098
#define IDC_TEX_SAMPLE_MODE             1099
#define IDC_BACKGROUND_COLOR_RESET      1101
#define IDC_FOG_RESET                   1102
#define IDC_NORMALS_SCALE_TEXTBOX       1103
#define ID_FILE_LOAD                    32771
#define ID_VIEW_ORTHOGRAPHIC            32772
#define ID_VIEW_PERSPECTIVE             32773
#define ID_ACTION_ROTATE                32774
#define ID_ACTION_TRANSLATE             32775
#define ID_ACTION_SCALE                 32776
#define ID_AXIS_X                       32777
#define ID_AXIS_Y                       32778
#define ID_AXIS_Z                       32779
#define ID_LIGHT_SHADING_FLAT           32781
#define ID_LIGHT_SHADING_GOURAUD        32782
#define ID_LIGHT_CONSTANTS              32783
#define ID_ANIM_PLAY                    32793
#define ID_ANIM_CLEAR                   32794
#define ID_ANIM_SNAPSHOT                32795
#define ID_BUTTON_SUBDIVIDE             32797
#define ID_OPTIONS_PERSPECTIVECONTROL   32798
#define ID_DRAW_BOUNDING_BOX            32801
#define ID_DRAW_SURFACE_NORMALS         32802
#define ID_DRAW_VERTEX_NORMALS          32803
#define ID_CAMERA_SPACE_TRANSFORM       32804
#define ID_OBJECT_SPACE_TRANSFORM       32805
#define ID_AXIS_COMBINED                32808
#define ID_ACTION_RESETVIEW             32811
#define ID_SEP_OBJECT_TRANSFORM         32812
#define ID_DRAW_AXES                    32814
#define ID_SHADING_PHONG                32816
#define ID_LIGHT_SHADING_PHONG          32817
#define ID_SHADING_WIREFRAME            32818
#define ID_SHADING_NONE                 32819
#define ID_OPTIONS_BACKFACESCULLING     32823
#define ID_TRANSFORMATION_SPACE         32825
#define ID_TRANSFORMATION_MODE          32826
#define ID_FILE_RESET                   32827
#define ID_RENDER_ONSCREEN              32828
#define ID_RENDER_TOFILE                32829
#define ID_OPTIONS_INVERSENORMALS       32832
#define ID_OPTIONS_INVERSEVERTEX_NORMALS 32833
#define ID_OPTIONS_INVERSESURFACENORMALS 32834
#define ID_SHADINGLIGHTNING_MATERIAL    32835
#define ID_BACKGROUND_LOAD              32836
#define ID_BACKGROUND_RESET             32837
#define ID_BACKGROUND_TILE              32838
#define ID_BACKGROUND_STRETCH           32839
#define ID_OPTIONS_DEPTHRENDERING       32840
#define ID_OPTIONS_PERSPECTIVECORRECTRENDERING 32841
#define ID_SHADINGLIGHTNING_LIGHTBACKFACES 32842
#define ID_DEBUG_DEBUGMODEL             32843
#define ID_DEBUG_INVERTDEPTH            32844
#define ID_DEBUG_FORCEALLFRONTFACES     32845
#define ID_OPTIONS_DRAWLIGHTSOURCES     32846

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32847
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
